// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArnoQwNn3vFBSlX45P94t6Yqz93gZvkYU',
    appId: '1:178280093013:web:7ff3cf0dd141e89e88cbdc',
    messagingSenderId: '178280093013',
    projectId: 'chat-app-168d2',
    authDomain: 'chat-app-168d2.firebaseapp.com',
    storageBucket: 'chat-app-168d2.appspot.com',
    measurementId: 'G-GK4QMG8B89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9-2R_S23IVzjMQYBRSRuu1niT-hy6ezI',
    appId: '1:178280093013:android:b2f9f56e7074e5a288cbdc',
    messagingSenderId: '178280093013',
    projectId: 'chat-app-168d2',
    storageBucket: 'chat-app-168d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmtrwK917ujxYI-1thMXe5UrMb3kZOuJA',
    appId: '1:178280093013:ios:586203220053750988cbdc',
    messagingSenderId: '178280093013',
    projectId: 'chat-app-168d2',
    storageBucket: 'chat-app-168d2.appspot.com',
    iosClientId: '178280093013-rubdu5d3hm9qfh7ub30bgaq5fue61fk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmtrwK917ujxYI-1thMXe5UrMb3kZOuJA',
    appId: '1:178280093013:ios:586203220053750988cbdc',
    messagingSenderId: '178280093013',
    projectId: 'chat-app-168d2',
    storageBucket: 'chat-app-168d2.appspot.com',
    iosClientId: '178280093013-rubdu5d3hm9qfh7ub30bgaq5fue61fk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
